### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by masudr4n4** [itzmeanjan/astroZ#1]
Hi @itzmeanjan 
 I am a designer want to make a logo for this project,I just need a permission to start my work.if you have any requirements then let me know.its free for open source projects.
Thanks

**Comment by itzmeanjan** [comment]
Hei @maaudrana, 
You're very much welcome to design logo for this project. Well I don't have any requirements, put your own idea into work.

**Let me know when you complete your work, I'll put a link back to your work.**

**Comment by Tobaloidee** [comment]
Hi @itzmeanjan , you want me to continue this issue?

**Comment by masudr4n4** [comment]
go ahead @Tobaloidee  pls

**Comment by itzmeanjan** [comment]
You're very welcome to work on it @Tobaloidee 

Would love to see your design :heart:

**Comment by Tobaloidee** [comment]
will work on it and show it here when done! @itzmeanjan  Thanks!

**Comment by Tobaloidee** [comment]
Thanks @maaudrana

**Comment by Tobaloidee** [comment]
here's what I came up with @itzmeanjan I hope you like it! 

colors applied was based from the projects screenshots

![pres 2-19](https://user-images.githubusercontent.com/36028424/57155947-4b653700-6e0f-11e9-92a7-4fe9acd2e976.png)



will make a PR when you do like it

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , this design looks good to me :heart: 

Please submit a PR and Thanks :smile:

**Comment by Tobaloidee** [comment]
Will do!! Thanks!😀

**Comment by Tobaloidee** [comment]
Here's the PR #2 with the logo upload & readme update @itzmeanjan  

You can also download all the versions & file formats [HERE](https://drive.google.com/drive/u/0/folders/1QqRRzlG9KjJjRxRQVyfY8eVb8ZoJn5eA)

Thanks & Best Regards!! Do you want me to make a logo for your other projects? I am willing! 😊

-Tobaloidee

**Comment by itzmeanjan** [comment]
Good work :+1: @Tobaloidee .

And yes, you're very welcome to work on other project's Logo Design :art:

**Comment by itzmeanjan** [comment]
And I've also updated readme with a small courtesy :blush:
